# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-04 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_details',
            old_name='table1',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='table1',
            new_name='cat',
        ),
    ]
